### PR TITLE
fix command parsing for unknown flags

### LINKED ISSUE #69: Command parsing fails silently when encountering undefined flags, causing package scanning to be ignored
When package manager commands contain flags that aren't defined in the respective parsers (pip, uv, poetry), the parsing fails silently and returns only the raw command without any install targets. This causes the package installation analysis to be completely skipped.

**Current Behavior:**
- Command: `pmg uv pip install --strict flask`
- Result: Parser returns `ParsedCommand` with zero install targets
- Issue: `flask` packages are not analyzed

**Expected Behavior:**
Parser should handle unknown flags gracefully and still analyze package's

### PR DESCRIPTION
**Pull request by Sahilb315**
Fixes #69

### CODE REVIEW

File: packagemanager/npm.go [hunk 1]
```diff
@@ -67,31 +69,49 @@ func (npm *npmPackageManager) ParseCommand(args []string) (*ParsedCommand, error
...
+		}
+	}
+
+	if installCmdIndex == -1 {
+		// No install command found, return as-is
+		return &ParsedCommand{Command: command}, nil
+	}
+
+	// Extract arguments after the install command
+	installArgs := args[installCmdIndex+1:]
```
Comment (abhisek) [inline packagemanager/npm.go:87]: We should test and ensure this does not overflow the array index

Comment (Sahilb315) [reply packagemanager/npm.go:87]: This wouldn't overflow, as slicing with a start index (eg. args[len(args):]) equal to the slice’s length returns an empty slice and does not cause a panic. As we are looping over the args itself, we wouldnt overflow
