### PR TITLE
fix: parsePackageInfo to handle pkg names with special character

### LINKED ISSUE #10: why are these `npm` install failing
Image

These packages npm install failed with exit code `1` but with no reason (output)

### PR DESCRIPTION
**Pull request by Sahilb315**
Fixes #10

### CODE REVIEW

File: pkg/common/utils/utils.go [hunk 1]
```diff
@@ -19,6 +19,17 @@ func ParsePackageInfo(input string) (packageName, version string, err error) {
 		return "", "", fmt.Errorf("package info cannot be empty")
 	}
 
+	if strings.HasPrefix(input, "@") {
```
Comment (OmkarPh) [inline pkg/common/utils/utils.go:23]: can you add tests for this and Cleanversion

File: pkg/wrapper/npm_base.go [hunk 2]
```diff
@@ -29,7 +29,7 @@ func NewPackageManagerWrapper(registryType registry.RegistryType) *PackageManage
 func (pmw *PackageManagerWrapper) Wrap() error {
 	ui.StartProgressWriter()
 
-	progressTracker := ui.TrackProgress(fmt.Sprintf("Scanning %s ", pmw.PackageName), 1)
+	progressTracker := ui.TrackProgress(fmt.Sprintf("Scanning %s ", pmw.PackageName), 5)
```
Comment (OmkarPh) [inline pkg/wrapper/npm_base.go:32]: why are we using "5" specifically here ?

Comment (Sahilb315) [reply pkg/wrapper/npm_base.go:32]: Currently the progress bar doesn't scale based on the number of dependencies being fetched & for value "1" it doesnt scale it until all the deps are fetched. Have added a issue for this & working on the fix - #12

Comment (OmkarPh) [reply pkg/wrapper/npm_base.go:32]: got it, but how does putting 5 instead of 1 help here ?

Comment (Sahilb315) [reply pkg/wrapper/npm_base.go:32]: When using the value 1 the progress bar used to be stuck & did not increment until the `TotalProgessValue` of the bar was not incremented (which was till `len(deps)`)
But using a little higher value the progress bar does update the value for fetching also but it was still a workaround & have fixed in the #14

Comment (OmkarPh) [reply pkg/wrapper/npm_base.go:32]: Oh alright
